on: push
name: build
jobs:
  go-pipeline:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@master
      - name: linter
        uses: shoukoo/golang-pipeline/go1.13/linter@master
      - name: tests
        uses: shoukoo/golang-pipeline/go1.13/test@master
